apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deployment.name }}
spec:
  serviceName: {{ .Values.deployment.name }}
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      role: "mongo"
  template:
    metadata:
      labels:
        role: "mongo"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.mongo.image }}
          command: ["mongod", "--replSet", "rs0", "--smallfiles", "--noprealloc"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: "mongo-persistent-storage"
              mountPath: "/data/db"
        - name: "mongo-sidecar"
          image: {{ .Values.mongoSidecar.image }}
          env:
            - name: "MONGO_SIDECAR_POD_LABELS"
              value: "role=mongo"
  volumeClaimTemplates:
    - metadata:
        name: "mongo-persistent-storage"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongo.storageClass }}
        resources:
          requests:
            storage: "5Gi"